id = "mage"
name = "mage"
version = "0.0.2"
schema_version = 1
authors = ["Alexander Kosachev <kosachev_alex@mail.ru>"]
description = "Mage support."
repository = "https://github.com/MageLanguage/zed-mage"

[language_servers.mage]
name = "Mage LS"
languages = ["Mage"]

[grammars.mage]
repository = "https://github.com/MageLanguage/tree-sitter-mage"
commit = "fa68ea9ca74d571b55db00f86fdbce0c1dc0ad14"
